/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'overview',
    'quickstart',
    'deploy',
    {
      type: 'category',
      label: '应用管理',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: "autogenerated",
          dirName: "application",
        },
      ],
    },
    {
      type: 'category',
      label: '成本中心',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: "autogenerated",
          dirName: "cost",
        },
      ],
    },
    {
      type: 'category',
      label: '运维中心',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: "autogenerated",
          dirName: "operation",
        },
      ],
    },
    {
      type: 'category',
      label: '系统设置',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: "autogenerated",
          dirName: "setting",
        }
      ]
    },
    'faq',
  ],
  openapi: [
    {
      type: "category",
      label: "API文档",
      link: {
        type: "generated-index",
        title: "API文档",
        slug: "/category/openapi",
      },
      items: require("./docs/openapi/sidebar.js"),
    },
  ],
};

module.exports = sidebars;
